controllers/AutoskloController.php
<?php


namespace app\controllers;


use yii\helpers\Html;
use yii\web\Controller;
use app\models\Bbbmenu;
//use app\models\Bbbnews;
use app\models\Bbbgallery;
use yii\web\NotFoundHttpException;
use Yii;

class AutoskloController extends Controller
{

    public $layout = 'autosklo';



    public function actionIndex()
    {
        // debug($_GET);
        $alias  = Yii::$app->request->get('alias'); // либо ($alias = null)
       // echo $alias;
        if ($alias == null) {
            $alias = 'index';
        }

        $data = Bbbmenu::find()->where(['alias' => $alias])->one();
        $gallery = $this->findModel(['model_id' => $data->id]);


        if ($data === null) { // item does not exist
            throw new \yii\web\HttpException(404, 'The requested Item could not be found.');
        }

        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => $data['description'],
        ]);
        \Yii::$app->view->registerMetaTag([
            'name' => 'keywords',
            'content' => $data['keywords'],
        ]);

        // debug($data);
        return $this->render('index', compact('data','gallery'));
    }

    public function actionSearch(){
        $q  = trim(Html::encode(Yii::$app->request->get('q')));
        if (!$q){
            return $this->render('search', compact('search','q'));
        }

        $search = Bbbmenu::find()->where(['like','body', $q])->all();

        return $this->render('search', compact('search','q'));

    }

    protected function findModel($id)
    {
        if (($gallery = Bbbgallery::findOne(['model_id' => $id])) !== null) {
            return $gallery;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/layouts/autosklo.php
<?php

use app\widgets\Alert;
use app\assets\AutoskloAsset;
use yii\widgets\Breadcrumbs;

use app\components\MenuWidget;



use yii\helpers\Html;
use yii\helpers\Url;

AutoskloAsset::register($this);
?>
<?php $this->beginPage() ?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
    <?php $this->head() ?>
    <title><?= Html::encode($this->title) ?></title>


</head>

<body>


<?php $this->beginBody() ?>
<div class="wrap">
    <div class="py-5">
        <div class="container">


            <div class="row">

               <!-- <div class="col-md-8" id="logo"><img class="img-fluid d-block rounded-circle" src="http://autosklo.in.ua/1/autosklo.png" id="logo_img"></div> -->
                <div class="col-md-8" id="logo">
                    <?= Html::a(Html::img('@web/images/autosklo.png',['class' => 'img-fluid d-block rounded-circle shadowfilter', 'id' => 'logo_img']), ['autosklo/index', 'alias' => 'index'])?>
                </div>
                <div class="col-md-4" id="phone">
                <!--    <img class="img-fluid d-block" src="http://autosklo.in.ua/slogan.png" id="phone_img"> -->
                <?= Html::img('@web/images/slogan.png',['id' => 'phone_img', 'class' => 'img-fluid d-block shadowfilter']) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="py-5">
        <div class="container">


            <div class="row">



                <div class="col-md-3 d-flex" id="menu">
                <div>
                    <?= MenuWidget::widget(['tpl' => 'menu'])?>
                </div>

                    <div id="search">
                        <form action="<?= Url::to(['autosklo/search']) ?>">
                            <input type="search" placeholder="Search" name="q" >
                        </form>
                    </div>

                </div>


<?php

//echo  print_r($this->params);
//echo count($this->context->actionParams);

$brd = $this->params['breadcrumbs'][0];

//debug($brd);
if($brd): ?>
                <div class="col-md-9">
                    <div>
                        <?php

                        if ($this->context->actionParams['alias'] != 'index'){
                            echo Breadcrumbs::widget([
                                'homeLink' => ['label' => 'Головна', 'url' => '/'],
                                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                            ]);
                        }
                         ?>
                        <?= Alert::widget() ?>
                    </div>

                        <div class="rounded shadow-sm" id="content" >

                        <?= $content ?>

                    </div>
                </div>
<?php endif;?>
            </div>
        </div>
    </div>
</div>

<div class="py-5" id="footer_div">
    <div class="container">
        <div class="row">
            <div class="col-md-12" id="footer">
            <p class="pull-left">&copy; Autosklo 2009 - <?= date('Y') ?></p>

        <p class="pull-right"><?= 'KK' ?></p>
            </div>
        </div>
    </div>
</div>

<!--
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
-->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/travel.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Genuine.community 2018 - <?= date('Y') ?></p>

        <p class="pull-right"><?= 'KK' ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>